#version: '3.8'

services:
  nginx:
    build: ./services/nginx
    container_name: nginx
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./services/nginx
          target: /
    depends_on:
      - api-gateway
      - front

  db:
    build: ./services/db
    container_name: db
    ports:
      - "2999:2999"
    volumes:
      - database:/app/data
    develop:
      watch:
        - action: sync
          path: ./services/db
          target: /app
          ignore:
            - node_modules/
    env_file:
      - .env
      
  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - game-service
    develop:
      watch:
        - action: sync
          path: ./services/api-gateway
          target: /app
          ignore:
            - node_modules/
    env_file:
      - .env

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    develop:
      watch:
        - action: sync
          path: ./services/auth-service
          target: /app
          ignore:
            - node_modules/
    env_file:
      - .env
    depends_on:
      - db

  front:
    build: ./services/front
    container_name: front
    ports:
      - 8000:8000
    volumes:
      - shared-avatars:/app/uploads/avatars
    depends_on:
      - api-gateway
      - auth-service
    develop:
      watch:
        - action: sync
          path: ./services/front
          target: /app
          ignore:
            - node_modules/

  game-service:
    build: ./services/game-service
    container_name: game-service
    ports:
      - "3002:3002"
    develop:
      watch:
        - action: sync
          path: ./services/game-service
          target: /app
          ignore:
            - node_modules/
    env_file:
      - .env
    depends_on:
      - db

  chat-service:
   build: ./services/chat-service
   container_name: chat-service
   ports:
     - "3003:3003"
   develop:
     watch:
       - action: sync
         path: ./services/chat-service
         target: /app
         ignore:
           - node_modules/
   env_file:
     - .env
   depends_on:
     - db

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "3004:3004"
    volumes:
      - shared-avatars:/app/uploads/avatars
    develop:
      watch:
        - action: sync
          path: ./services/user-service
          target: /app
          ignore:
            - node_modules/
    env_file:
      - .env
    depends_on:
      - db

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/services/db/database
  shared-avatars:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/shared/avatars