GET http://localhost:3004/friend/gamestats/pong/guest HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiYXZhdGFyIjpudWxsLCJpYXQiOjE3NDQzODM1OTJ9.C1cn2x2DYmU94Ku6eTSZBUpFRs7vbsdmIbB_y2PVa3c