PATCH http://localhost:3000/chat/friend/accept HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiYXZhdGFyIjoidXBsb2Fkcy9hdmF0YXJzLzItdGVzdC5qcGciLCJpYXQiOjE3NDQyODkyNDF9.0mAqBZI655jSQr55SEFt05afmz0dIbXGntQc0bP14EQ

{
    "friendusername": "test2"
}
